---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "test"
    mypassword: "test@12345"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ myuser }}"
        update_password: always
        password: "{{ mypassword | password_hash('sha512') }}"


